pipeline {
     environment {
        registryCredential = 'dockerHub'
        imagename = 'apanisile/k8s-mastery'
        dockerImage = ''
    }
    agent any
    stages {
        stage('Build React Frontend') { 
            steps {
                sh 'cd frontend && npm install' 
            }
        }
         stage('Test') { 
            steps {
                sh 'npm test' 
            }
        }
    }
}