pipeline {
     environment {
        registryCredential = 'dockerHub'
        imagename = 'apanisile/k8s-mastery'
        dockerImage = ''
    }
    agent any
    stages {
        stage('Build & Test React Frontend') { 
            steps {
                sh 'cd frontend && npm install'
            }
        }
        stage('Build & Test Webapp') { 
            steps {
                sh 'cd webapp && mvn clean package'
                
            }
        }
         
    }
}